import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { firstName, lastName, jerseyNumber, pin, teamId } = await req.json()

    // Validate inputs
    if (!firstName || !lastName || !jerseyNumber || !pin || !teamId) {
      throw new Error('Missing required fields: firstName, lastName, jerseyNumber, pin, teamId')
    }

    if (pin.length !== 4 || !/^\d{4}$/.test(pin)) {
      throw new Error('PIN must be exactly 4 digits')
    }

    // Get caller's auth
    const authHeader = req.headers.get('Authorization')
    const token = authHeader?.replace('Bearer ', '')

    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: `Bearer ${token}` } } }
    )

    const { data: { user: caller } } = await supabaseClient.auth.getUser()
    console.log('[create-player] Caller:', caller?.id, caller?.email)
    if (!caller) throw new Error('Unauthorized - no valid session')

    // Verify caller is guardian/coach/manager/director for this team
    const { data: membership, error: membershipError } = await supabaseClient
      .from('team_memberships')
      .select('role')
      .eq('team_id', teamId)
      .eq('user_id', caller.id)
      .single()

    console.log('[create-player] Team ID:', teamId)
    console.log('[create-player] Membership lookup:', membership, 'Error:', membershipError)

    const allowedRoles = ['parent', 'coach', 'manager', 'director']
    if (!membership || !allowedRoles.includes(membership.role)) {
      throw new Error(`Not authorized to create players for this team. Role: ${membership?.role || 'none'}`)
    }

    // Create auth user with service role (no password)
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    const displayName = `${firstName}${jerseyNumber}`
    const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}.${jerseyNumber}@firefc.internal`

    const { data: authUser, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email: email,
      email_confirm: true,
      user_metadata: {
        full_name: `${firstName} ${lastName}`,
        display_name: displayName,
        role: 'player',
        jersey_number: jerseyNumber,
        player_pin: pin
      }
    })

    if (authError) throw authError

    try {
      // Create player identity row. team_id/jersey_number on `players` are
      // now legacy "primary team" pointers — the source of truth for roster
      // membership is `player_teams`. We still populate them so older
      // read-paths that haven't migrated yet keep working.
      const { data: playerRow, error: playerError } = await supabaseAdmin
        .from('players')
        .insert({
          user_id: authUser.user.id,
          team_id: teamId,
          first_name: firstName,
          last_name: lastName,
          jersey_number: jerseyNumber,
          display_name: displayName
        })
        .select('id, guardian_code')
        .single()

      if (playerError) throw playerError

      // Active membership on player_teams (authoritative source).
      const { error: ptError } = await supabaseAdmin.from('player_teams').insert({
        player_id: playerRow.id,
        team_id: teamId,
        jersey_number: jerseyNumber,
        status: 'active'
      })

      if (ptError) throw ptError

      // Create team membership
      const { error: membershipError } = await supabaseAdmin.from('team_memberships').insert({
        team_id: teamId,
        user_id: authUser.user.id,
        role: 'player'
      })

      if (membershipError) throw membershipError

      // If caller is parent, create guardian relationship
      if (membership.role === 'parent') {
        await supabaseAdmin.from('player_guardians').insert({
          player_user_id: authUser.user.id,
          guardian_user_id: caller.id,
          relationship: 'parent'
        })
      }

      return new Response(JSON.stringify({
        success: true,
        // player_id is the players row id (for roster/invite flows). user_id
        // is the auth.users id (for client-side identification). Both are
        // returned so the caller can pick. guardian_code is the 6-char
        // parent-link code generated by the BEFORE-INSERT trigger.
        player_id: playerRow.id,
        user_id: authUser.user.id,
        display_name: displayName,
        first_name: firstName,
        last_name: lastName,
        jersey_number: jerseyNumber,
        guardian_code: playerRow.guardian_code
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    } catch (error) {
      // Rollback: delete auth user
      await supabaseAdmin.auth.admin.deleteUser(authUser.user.id)
      throw error
    }
  } catch (error) {
    console.error('Error creating player:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})
