import React, { useEffect, useState } from 'react';
import { X, Shield, Copy, Check, MessageSquare, Mail, Users, Link as LinkIcon } from 'lucide-react';
import { supabase } from '../../supabaseClient';
import { useToast } from '../Toast';
import { buildInviteUrl } from '../../utils/pendingInvite';

// Invite a player's family via a one-tap deep link (preferred) or the
// permanent 6-char guardian code as a fallback. The link
// (firefcapp.com/login?join=CODE) carries the code into the app so the
// parent is auto-linked after signup — no typing, no roster hunt.
//
// The code lives on players.guardian_code and is auto-generated by a
// DB trigger when a player is created. If the prop comes in without a
// code attached, we fetch it.
const FamilyInviteModal = ({ player, onClose }) => {
    const toast = useToast();
    const [code, setCode] = useState(player?.guardian_code || '');
    const [copied, setCopied] = useState(false);
    const [copiedLink, setCopiedLink] = useState(false);
    const [loading, setLoading] = useState(!player?.guardian_code);

    useEffect(() => {
        let cancelled = false;
        const fetchCode = async () => {
            if (player?.guardian_code) return;
            if (!player?.id) return;
            const { data, error } = await supabase
                .from('players')
                .select('guardian_code')
                .eq('id', player.id)
                .maybeSingle();
            if (cancelled) return;
            if (error) {
                console.error('[FamilyInviteModal] code fetch failed', error);
                toast.error("Couldn't load the guardian code.");
            } else if (data?.guardian_code) {
                setCode(data.guardian_code);
            }
            setLoading(false);
        };
        fetchCode();
        return () => { cancelled = true; };
    }, [player?.id, player?.guardian_code]);

    const inviteUrl = buildInviteUrl(code);

    const handleCopy = () => {
        if (!code) return;
        navigator.clipboard.writeText(code);
        setCopied(true);
        toast.success('Code copied.');
        setTimeout(() => setCopied(false), 2000);
    };

    const handleCopyLink = () => {
        if (!inviteUrl) return;
        navigator.clipboard.writeText(inviteUrl);
        setCopiedLink(true);
        toast.success('Invite link copied.');
        setTimeout(() => setCopiedLink(false), 2000);
    };

    // SMS / email body — lead with the tap-to-join link; code is the backup.
    const playerName = player?.name || `${player?.firstName || ''} ${player?.lastName || ''}`.trim() || 'your player';
    const smsBody = encodeURIComponent(
        `Join ${playerName} on the Fire FC app — tap this link, sign up, and you're connected automatically:\n${inviteUrl}\n\n(If the link doesn't work, go to firefcapp.com, sign up, and enter code ${code}.)`
    );
    const emailSubject = encodeURIComponent(`Fire FC parent invite for ${playerName}`);
    const emailBody = encodeURIComponent(
        `Hi,\n\nTap this link to connect to ${playerName} in the Fire FC app — just sign up and you'll be linked automatically:\n\n${inviteUrl}\n\nIf the link doesn't open, go to firefcapp.com, tap Sign Up, then enter this code when asked: ${code}\n\nThanks!\nCoach`
    );

    return (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-end md:items-center justify-center md:p-4 animate-fade-in">
            <div className="bg-brand-dark border border-white/10 rounded-t-2xl md:rounded-2xl w-full md:max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl relative">
                <button
                    onClick={onClose}
                    className="absolute top-4 right-4 text-gray-400 hover:text-white transition-colors"
                >
                    <X className="w-6 h-6" />
                </button>

                <div className="p-6 md:p-8 pb-[max(2rem,env(safe-area-inset-bottom)+1.5rem)]">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="w-14 h-14 rounded-full bg-brand-gold/15 text-brand-gold flex items-center justify-center border-2 border-brand-gold/40">
                            <Shield className="w-6 h-6" />
                        </div>
                        <div className="min-w-0">
                            <h2 className="text-xl md:text-2xl font-display font-bold text-white uppercase tracking-wider truncate">
                                Invite {playerName}'s family
                            </h2>
                            <p className="text-brand-green font-bold text-xs uppercase tracking-widest mt-0.5">
                                #{player?.number || '--'} • Share with both parents
                            </p>
                        </div>
                    </div>

                    {/* Invite link panel — the primary, easiest path */}
                    <div className="bg-gradient-to-br from-brand-green/20 via-brand-green/5 to-transparent border border-brand-green/40 rounded-xl p-5 mb-4">
                        <p className="text-[10px] text-brand-green uppercase tracking-widest font-bold mb-1.5">Tap-to-join link</p>
                        <div className="flex items-center justify-between gap-2">
                            <div className="font-mono text-sm text-gray-200 truncate">
                                {loading ? 'loading…' : (inviteUrl || '—')}
                            </div>
                            <button
                                onClick={handleCopyLink}
                                disabled={!inviteUrl}
                                className="shrink-0 px-3 py-2 bg-brand-green/20 hover:bg-brand-green/30 disabled:opacity-40 rounded-lg flex items-center gap-1.5 text-brand-green text-xs font-bold uppercase tracking-wider"
                            >
                                {copiedLink
                                    ? <><Check className="w-3.5 h-3.5" /> Copied</>
                                    : <><LinkIcon className="w-3.5 h-3.5" /> Copy link</>}
                            </button>
                        </div>
                        <p className="text-[11px] text-gray-400 mt-3 leading-snug">
                            They tap the link, sign up, and are linked to {playerName} automatically — no code to type. Same link works for both parents.
                        </p>
                    </div>

                    {/* Guardian code panel — fallback if the link won't open */}
                    <div className="bg-gradient-to-br from-brand-gold/20 via-brand-gold/5 to-transparent border border-brand-gold/40 rounded-xl p-5 mb-5">
                        <p className="text-[10px] text-brand-gold uppercase tracking-widest font-bold mb-1.5">Backup code</p>
                        <div className="flex items-center justify-between gap-2">
                            <div className="font-mono text-4xl md:text-5xl font-bold tracking-[0.25em] text-white">
                                {loading ? '······' : (code || '------')}
                            </div>
                            <button
                                onClick={handleCopy}
                                disabled={!code}
                                className="px-3 py-2 bg-white/10 hover:bg-white/20 disabled:opacity-40 rounded-lg flex items-center gap-1.5 text-white text-xs font-bold uppercase tracking-wider"
                            >
                                {copied
                                    ? <><Check className="w-3.5 h-3.5 text-brand-green" /> Copied</>
                                    : <><Copy className="w-3.5 h-3.5" /> Copy</>}
                            </button>
                        </div>
                        <p className="text-[11px] text-gray-400 mt-3 leading-snug">
                            If the link won't open, the family signs up at firefcapp.com and enters this code on the "Select your child" step (tap "Use code instead"). Permanent; same code for both parents and any fan.
                        </p>
                    </div>

                    {/* Share buttons */}
                    <div className="grid grid-cols-2 gap-3 mb-2">
                        <a
                            href={code ? `sms:?body=${smsBody}` : undefined}
                            onClick={(e) => { if (!code) e.preventDefault(); }}
                            className={`flex items-center justify-center gap-2 px-4 py-3 rounded-xl border font-bold uppercase text-xs tracking-wider transition-all ${code
                                ? 'bg-brand-green/10 border-brand-green/40 text-brand-green hover:bg-brand-green/20'
                                : 'bg-white/5 border-white/10 text-gray-500 cursor-not-allowed'}`}
                        >
                            <MessageSquare className="w-4 h-4" /> Text
                        </a>
                        <a
                            href={code ? `mailto:?subject=${emailSubject}&body=${emailBody}` : undefined}
                            onClick={(e) => { if (!code) e.preventDefault(); }}
                            className={`flex items-center justify-center gap-2 px-4 py-3 rounded-xl border font-bold uppercase text-xs tracking-wider transition-all ${code
                                ? 'bg-purple-500/10 border-purple-500/40 text-purple-300 hover:bg-purple-500/20'
                                : 'bg-white/5 border-white/10 text-gray-500 cursor-not-allowed'}`}
                        >
                            <Mail className="w-4 h-4" /> Email
                        </a>
                    </div>

                    <p className="text-[11px] text-gray-500 mt-4 flex items-start gap-2">
                        <Users className="w-3 h-3 mt-0.5 shrink-0" />
                        <span>When they sign up, they'll choose their relationship and enter their name and phone — so you can reach them — then they're connected.</span>
                    </p>
                </div>
            </div>
        </div>
    );
};

export default FamilyInviteModal;
