-- Winter portal open-tracking + staff stats/roster.
-- Anonymous visits are logged (once per visit_id per day) so staff can see how
-- many people open the link. Staff-only RPCs expose opens, commits, questions,
-- and the full committed roster (names + contact) — the "coaches" view.

create table if not exists public.winter_visits (
    id         bigint generated by default as identity primary key,
    org_id     uuid not null references public.organizations(id),
    visit_id   text,
    path       text,
    created_at timestamptz not null default now()
);
alter table public.winter_visits enable row level security;  -- access via RPCs only
create index if not exists winter_visits_org_idx on public.winter_visits(org_id, created_at);

-- ANON: log a visit, deduped to one row per visit_id per day (Central).
create or replace function public.log_winter_visit(p_org_slug text, p_visit_id text, p_path text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v_org uuid;
begin
    select id into v_org from public.organizations where slug = p_org_slug and deleted_at is null;
    if v_org is null then return; end if;
    if p_visit_id is not null and exists(
        select 1 from public.winter_visits w
        where w.org_id = v_org and w.visit_id = p_visit_id
          and (w.created_at at time zone 'America/Chicago')::date = (now() at time zone 'America/Chicago')::date
    ) then return; end if;
    insert into public.winter_visits(org_id, visit_id, path) values (v_org, p_visit_id, p_path);
end;
$$;

-- STAFF: headline stats + opens-by-day.
create or replace function public.winter_stats_admin(p_org_slug text)
returns json language plpgsql stable security definer set search_path = public as $$
declare v_org uuid; v_res json;
begin
    select id into v_org from public.organizations where slug = p_org_slug;
    if v_org is null or not public._rc_is_org_staff(v_org) then raise exception 'not authorized'; end if;
    select json_build_object(
        'opens_total',       (select count(*) from public.winter_visits where org_id = v_org),
        'unique_visitors',   (select count(distinct visit_id) from public.winter_visits where org_id = v_org),
        'commits',           (select count(*) from public.winter_signups where org_id = v_org and status = 'committed'),
        'questions_pending', (select count(*) from public.winter_questions where org_id = v_org and status = 'pending'),
        'questions_total',   (select count(*) from public.winter_questions where org_id = v_org and status <> 'hidden'),
        'opens_by_day',      (select coalesce(json_agg(row_to_json(d) order by d.day), '[]') from (
                                 select to_char((created_at at time zone 'America/Chicago')::date, 'MM-DD') as day, count(*) as opens
                                 from public.winter_visits where org_id = v_org and created_at > now() - interval '14 days'
                                 group by 1) d)
    ) into v_res;
    return v_res;
end;
$$;

-- STAFF: full committed roster with contact (the "coaches" info view).
create or replace function public.list_winter_signups_admin(p_org_slug text)
returns table(player_first text, player_last text, dob date, age_group text,
              guardian_name text, guardian_email text, guardian_phone text, status text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
    select ws.player_first_name, ws.player_last_name, ws.player_dob, t.age_group,
           ws.guardian_name, ws.guardian_email, ws.guardian_phone, ws.status, ws.created_at
    from public.winter_signups ws
    join public.teams t on t.id = ws.team_id
    join public.organizations o on o.id = ws.org_id
    where o.slug = p_org_slug and public._rc_is_org_staff(ws.org_id)
    order by ws.created_at desc;
$$;

grant execute on function public.log_winter_visit(text, text, text) to anon, authenticated;
grant execute on function public.winter_stats_admin(text) to authenticated;
grant execute on function public.list_winter_signups_admin(text) to authenticated;
